name         'fernandoalmeida-rbenv-ruby'
version      '0.0.1'
source       'https://github.com/fernandoalmeida/puppet-rbenv-ruby.git'
author       'Fernando Almeida'
license      'Apache License, Version 2.0'
summary      'A Puppet module for installing and configuring Ruby with Rbenv'
description  'A Puppet module for installing and configuring Ruby with Rbenv'
project_page 'https://github.com/fernandoalmeida/puppet-rbenv-ruby'
